version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: test-db-bsc
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
  
  bot:
    container_name: test-bot-bsc
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./Makefile:/app/Makefile
      - ./.env.test:/app/.env.test
      - ./app:/app/app
    depends_on:
      - db
    command: ["make", "test-bot"]
  
