"""empty message

Revision ID: 835828b96535
Revises: d6bdb7342523
Create Date: 2023-09-09 15:22:28.430457

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "835828b96535"
down_revision = "d6bdb7342523"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "wallet", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "wallet", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
