"""empty message

Revision ID: d6bdb7342523
Revises: 6cf34952990b
Create Date: 2023-09-08 20:05:29.587201

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d6bdb7342523"
down_revision = "6cf34952990b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("wallet", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "wallet")
    # ### end Alembic commands ###
